import { createContext, useContext, useState, type ReactNode } from 'react';
import { Link, useLocation } from '@tanstack/react-router';
import { Bell, House, Pill, CalendarDays, ShoppingBasket, Users, ChevronRight, Plus, Sparkles, ShieldCheck, Check, Clock3, MoreHorizontal, ArrowUpRight, Wallet, ScanLine, Camera, ChevronLeft, Copy, Heart, Circle, CheckCircle2, ArrowLeftRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import homeImage from '@/assets/kubo-home.png';

export const members = [
  { name:'You', role:'Daughter', emoji:'👩🏻', color:'bg-peach', birthday:'March 12' },
  { name:'Mom', role:'Mother', emoji:'👩🏻‍🦱', color:'bg-lilac', birthday:'May 24' },
  { name:'Dad', role:'Father', emoji:'👨🏻', color:'bg-sky', birthday:'September 8' },
  { name:'Kuya', role:'Brother', emoji:'👦🏻', color:'bg-secondary', birthday:'January 19' },
  { name:'Lola', role:'Grandmother', emoji:'👵🏻', color:'bg-peach', birthday:'November 2' },
];
type Medicine = { id:number; name:string; dosage:string; person:string; time:string; stock:number; status:string; type:string };
type Event = { id:number; title:string; day:number; time:string; member:string; location:string };
type Grocery = { id:number; name:string; category:string; checked:boolean; quantity:string };
type ModalKind = 'magic' | 'scan' | 'medicine' | 'event' | 'grocery' | 'debt' | 'invite' | 'notifications' | 'member' | null;
function useDemoState() {
 const [medicines,setMedicines] = useState<Medicine[]>([
  {id:1,name:'Losartan',dosage:'50 mg · 1 tablet',person:'Lola',time:'8:00 AM',stock:12,status:'Due now',type:'Maintenance'},
  {id:2,name:'Vitamin C',dosage:'500 mg · 1 tablet',person:'You',time:'9:00 AM',stock:24,status:'Upcoming',type:'Maintenance'},
  {id:3,name:'Paracetamol',dosage:'500 mg · 1 tablet',person:'Dad',time:'As needed',stock:8,status:'As needed',type:'PRN'},
 ]);
 const [events,setEvents] = useState<Event[]>([
  {id:1,title:'Lola’s check-up',day:9,time:'3:00 PM',member:'Lola',location:'Makati Medical Center'},
  {id:2,title:'Family dinner',day:10,time:'6:30 PM',member:'Everyone',location:'At home'},
  {id:3,title:'Mom’s grocery run',day:11,time:'10:00 AM',member:'Mom',location:'Weekend market'},
 ]);
 const [groceries,setGroceries] = useState<Grocery[]>([
  {id:1,name:'Bananas',category:'Produce',checked:false,quantity:'1 bunch'},
  {id:2,name:'Tomatoes',category:'Produce',checked:false,quantity:'500 g'},
  {id:3,name:'Fresh milk',category:'Dairy & eggs',checked:false,quantity:'1 carton'},
  {id:4,name:'Eggs',category:'Dairy & eggs',checked:false,quantity:'1 dozen'},
  {id:5,name:'Rice',category:'Pantry',checked:false,quantity:'5 kg'},
  {id:6,name:'Bread',category:'Pantry',checked:false,quantity:'1 loaf'},
  {id:7,name:'Dish soap',category:'Household',checked:false,quantity:'1 bottle'},
  {id:8,name:'Chicken',category:'Meat',checked:true,quantity:'1 kg'},
 ]);
 const [debts,setDebts] = useState([{id:1,name:'Dad',amount:200,reason:'Pizza night',direction:'owe',settled:false},{id:2,name:'Kuya',amount:150,reason:'Coffee & snacks',direction:'owed',settled:false}]);
 const [modal,setModal] = useState<ModalKind>(null);
 const [selectedMember,setSelectedMember] = useState(members[0]);
 const [notice,setNotice] = useState('');
 const notify=(text:string)=>{setNotice(text);window.setTimeout(()=>setNotice(''),3000);};
 return {medicines,setMedicines,events,setEvents,groceries,setGroceries,debts,setDebts,modal,setModal,selectedMember,setSelectedMember,notice,notify};
}
type DemoContext = ReturnType<typeof useDemoState>;
const KuboContext = createContext<DemoContext | null>(null);
export function useKubo(){const ctx=useContext(KuboContext);if(!ctx)throw new Error('Kubo provider missing');return ctx;}
export function KuboProvider({children}:{children:ReactNode}) {const state=useDemoState();return <KuboContext.Provider value={state}>{children}</KuboContext.Provider>;}
const navigation = [
 {to:'/' as const,label:'Home',icon:House},
 {to:'/medicine' as const,label:'Medicine',icon:Pill},
 {to:'/calendar' as const,label:'Calendar',icon:CalendarDays},
 {to:'/lists' as const,label:'Lists',icon:ShoppingBasket},
 {to:'/family' as const,label:'Circle',icon:Users},
];
export function KuboShell({children}:{children:ReactNode}) {
 const ctx=useKubo();const location=useLocation();
 return <div className="app-shell">
  <header className="app-header"><Link to="/" className="brand" aria-label="Kubo home"><House className="brand-icon" strokeWidth={2.5}/>kubo<span className="text-primary">.</span></Link><div className="header-actions"><Button variant="plain" size="touch" className="header-bell" aria-label="Notifications" onClick={()=>ctx.setModal('notifications')}><Bell className="size-5"/></Button><Button variant="plain" size="touch" aria-label="Your profile" onClick={()=>{ctx.setSelectedMember(members[0]);ctx.setModal('member');}}><span className="profile-dot">M</span></Button></div></header>
  <main className="page-body page-enter" key={location.pathname}>{children}</main>
  <nav className="nav-bar" aria-label="Main navigation">{navigation.map(({to,label,icon:Icon})=><Button key={to} variant="navigation" asChild className={`nav-item ${location.pathname===to || (to==='/lists' && location.pathname==='/money')?'active':''}`}><Link to={to}><Icon strokeWidth={location.pathname===to?2.3:1.7}/><span>{label}</span></Link></Button>)}</nav>
  <PrototypeDialogs/>{ctx.notice&&<div className="toast-note" role="status">{ctx.notice}</div>}
 </div>;
}
export function SectionTitle({title,to,action,label='View all'}:{title:string;to?:'/'|'/medicine'|'/calendar'|'/lists'|'/family'|'/money';action?:()=>void;label?:string}) {return <div className="section-title"><h2>{title}</h2>{to?<Button variant="link" asChild className="text-link h-auto p-0"><Link to={to}>{label}<ChevronRight className="size-3"/></Link></Button>:action?<Button variant="link" className="text-link h-auto p-0" onClick={action}>{label}<ChevronRight className="size-3"/></Button>:null}</div>;}
function MemberAvatar({name,size=''}:{name:string;size?:string}) {const member=members.find(m=>m.name===name)??members[0];return <span className={`member-avatar ${member?.color??'bg-secondary'} ${size}`}>{name==='You'?'M':name==='Mom'?'M':name==='Dad'?'D':name==='Kuya'?'K':'L'}</span>;}
export function DoseCard({medicine}:{medicine:Medicine}) {
 const ctx=useKubo();const update=(status:string)=>ctx.setMedicines(items=>items.map(m=>m.id===medicine.id?{...m,status}:m));
 return <article className="dose-card"><div className="dose-header"><span className="feature-icon bg-secondary text-primary"><Pill className="size-5"/></span><div className="min-w-0"><h3>{medicine.name}</h3><p>{medicine.dosage}</p></div><span className={`pill-label ${medicine.status==='Due now'?'bg-peach text-peach-ink':'bg-secondary text-primary'}`}>{medicine.status}</span></div><div className="dose-detail"><Clock3 className="size-3.5"/><span>{medicine.time}</span><span className="mx-1">·</span><span>{medicine.person}</span><span className="ml-auto pill-label bg-muted">{medicine.type}</span></div>{medicine.status==='Taken'?<Button variant="soft" className="w-full h-11" onClick={()=>update('Due now')}><CheckCircle2/>Taken · undo</Button>:<div className="dose-actions"><Button variant="mobile" onClick={()=>update('Taken')}><Check/>Mark as taken</Button><Button variant="outline" size="touch" title="Snooze for 10 minutes" aria-label={`Snooze ${medicine.name}`} onClick={()=>{update('Snoozed');ctx.notify('Reminder snoozed · preview');}}><Clock3/></Button><Button variant="outline" size="touch" title="Skip this dose" aria-label={`Skip ${medicine.name}`} onClick={()=>update('Skipped')}><MoreHorizontal/></Button></div>}<div className="dose-footer"><Users className="size-3"/>Visible to your family<span className="ml-auto">{medicine.stock} tablets left</span></div></article>;
}
export function EventRow({event}:{event:Event}){return <div className="event-row"><div className="date-tile"><span>OCT</span><strong>{event.day}</strong></div><div className="min-w-0"><h3>{event.title}</h3><p>{event.time} <span className="mx-1">·</span> {event.member}</p></div><span className="pill-label bg-secondary text-primary">{event.member==='Everyone'?'All':event.member}</span></div>;}
export function HomeView() {
 const ctx=useKubo();const remaining=ctx.groceries.filter(g=>!g.checked).length;
 return <><section className="welcome"><div className="eyebrow">FRIDAY, OCTOBER 9</div><h1>Good morning, Mia <span className="text-xl">☀️</span></h1><p>A little care. A happier home.</p><img className="welcome-image" src={homeImage} alt="A welcoming green bahay kubo" width={1024} height={1024}/></section>
 <SectionTitle title="Your family circle" to="/family" label="See all"/>
 <div className="family-strip">{members.map(m=><Button variant="plain" key={m.name} className="member h-auto p-0 hover:bg-transparent" onClick={()=>{ctx.setSelectedMember(m);ctx.setModal('member');}}><MemberAvatar name={m.name}/><span className="member-name">{m.name}</span></Button>)}</div>
 <Button variant="soft" className="magic-banner w-full h-auto whitespace-normal text-left" onClick={()=>ctx.setModal('magic')}><span className="magic-icon"><Sparkles className="size-5"/></span><span className="min-w-0"><h3>A little magic for your day</h3><p>Add it in your own words. We’ll sort it out.</p></span><ChevronRight className="text-primary"/></Button>
 <SectionTitle title="A dose of care" to="/medicine"/>{ctx.medicines[0]&&<DoseCard medicine={ctx.medicines[0]}/>}
 <section className="mt-7"><SectionTitle title="Around the house"/><div className="quick-grid">
 <QuickCard to="/calendar" icon={<CalendarDays/>} color="bg-sky text-sky-ink" title="Family calendar" text="2 events coming up"/>
 <QuickCard to="/lists" icon={<ShoppingBasket/>} color="bg-peach text-peach-ink" title="Grocery list" text={`${remaining} items to pick up`}/>
 <QuickCard to="/money" icon={<Wallet/>} color="bg-lilac text-lilac-ink" title="Family balances" text="A little give & take"/>
 <QuickCard to="/medicine" icon={<Pill/>} color="bg-secondary text-primary" title="Medicine cabinet" text={`${ctx.medicines.length} medicines · all in one place`}/>
 </div></section><section className="mt-7"><SectionTitle title="Coming up" to="/calendar"/>{ctx.events.slice(0,2).map(e=><EventRow key={e.id} event={e}/>)}</section><div className="mt-6 flex justify-center items-center gap-1.5 text-[10px] text-muted-foreground"><ShieldCheck className="size-3"/>Your family. Your device. Your peace of mind.</div></>;
}
function QuickCard({to,icon,color,title,text}:{to:'/calendar'|'/lists'|'/money'|'/medicine';icon:ReactNode;color:string;title:string;text:string}) {return <Button variant="tile" asChild className="quick-card h-auto whitespace-normal"><Link to={to}><span className={`feature-icon ${color}`}>{icon}</span><ArrowUpRight className="corner-arrow"/><h3>{title}</h3><p>{text}</p></Link></Button>;}
export function MedicineView() {const ctx=useKubo();const [filter,setFilter]=useState('All');return <><PageHeading title="A dose of care" subtitle="Looking after each other, every day." onAdd={()=>ctx.setModal('medicine')}/><Button variant="soft" className="w-full h-12 mb-5" onClick={()=>ctx.setModal('scan')}><ScanLine/>Scan a medicine</Button><div className="segmented">{['All','Maintenance','PRN'].map(f=><Button key={f} variant={filter===f?'tile':'plain'} onClick={()=>setFilter(f)}>{f}</Button>)}</div><div className="grid gap-4">{ctx.medicines.filter(m=>filter==='All'||m.type===filter).map(m=><DoseCard key={m.id} medicine={m}/>)}</div><p className="prototype-note mt-6 flex gap-2"><ShieldCheck className="size-4 shrink-0"/>Kubo is a reminder tool, not medical advice. Follow your doctor’s or pharmacist’s instructions.</p></>;}
export function PageHeading({title,subtitle,onAdd}:{title:string;subtitle:string;onAdd?:()=>void}){return <div className="page-heading"><div className="min-w-0"><h1>{title}</h1><p>{subtitle}</p></div>{onAdd&&<Button variant="mobile" size="touch" aria-label={`Add to ${title}`} onClick={onAdd}><Plus/></Button>}</div>;}
export function CalendarView(){const ctx=useKubo();const [mode,setMode]=useState('Month');const [day,setDay]=useState(9);const [month,setMonth]=useState(9);const monthNames=['January','February','March','April','May','June','July','August','September','October','November','December'];const date=new Date(2026,month,1);const count=new Date(2026,month+1,0).getDate();return <><PageHeading title="Family calendar" subtitle="Make time for what matters." onAdd={()=>ctx.setModal('event')}/><div className="segmented">{['Month','Agenda'].map(m=><Button key={m} variant={mode===m?'tile':'plain'} onClick={()=>setMode(m)}>{m}</Button>)}</div>{mode==='Month'&&<><div className="flex justify-between items-center mb-4"><Button variant="plain" size="touch" aria-label="Previous month" onClick={()=>setMonth(m=>Math.max(0,m-1))}><ChevronLeft/></Button><h2 className="font-bold">{monthNames[month]} 2026</h2><Button variant="plain" size="touch" aria-label="Next month" onClick={()=>setMonth(m=>Math.min(11,m+1))}><ChevronRight/></Button></div><div className="calendar-grid mb-7">{['S','M','T','W','T','F','S'].map((d,i)=><span key={i} className="text-xs text-muted-foreground h-7">{d}</span>)}{Array.from({length:date.getDay()},(_,i)=><span key={`blank${i}`}/>)}{Array.from({length:count},(_,i)=>i+1).map(d=><Button key={d} variant="plain" className={`calendar-day p-0 ${day===d?'selected':''} ${month===9&&ctx.events.some(e=>e.day===d)?'has-event':''}`} onClick={()=>setDay(d)}>{d}</Button>)}</div></>}<SectionTitle title={mode==='Month'?`${monthNames[month]} ${day}`:'Upcoming together'}/>{(mode==='Agenda'?ctx.events:month===9?ctx.events.filter(e=>e.day===day):[]).map(e=><EventRow event={e} key={e.id}/>)}{mode==='Month'&&!(month===9&&ctx.events.some(e=>e.day===day))&&<div className="py-10 text-center text-muted-foreground"><CalendarDays className="mx-auto mb-3 size-8"/><p className="text-sm">A little breathing room.</p><Button variant="link" onClick={()=>ctx.setModal('event')}>Add an event</Button></div>}</>;}
export function ListsView(){const ctx=useKubo();const [tab,setTab]=useState('Groceries');const [paid,setPaid]=useState(false);const remaining=ctx.groceries.filter(g=>!g.checked).length;return <><PageHeading title="Household lists" subtitle="Less remembering. More living." onAdd={()=>ctx.setModal('grocery')}/><div className="segmented">{['Groceries','Bills'].map(t=><Button key={t} variant={tab===t?'tile':'plain'} onClick={()=>setTab(t)}>{t}</Button>)}</div>{tab==='Groceries'?<><div className="flex justify-between mb-6"><span className="text-sm font-semibold">{remaining} items to pick up</span><span className="text-xs text-muted-foreground">Shared with everyone</span></div>{Array.from(new Set(ctx.groceries.map(g=>g.category))).map(category=><section key={category} className="mb-5"><h2 className="text-[11px] uppercase font-bold text-muted-foreground">{category}</h2>{ctx.groceries.filter(g=>g.category===category).map(g=><div className="list-row" key={g.id}><Button variant="plain" size="touch" role="checkbox" aria-checked={g.checked} aria-label={`Check ${g.name}`} onClick={()=>ctx.setGroceries(items=>items.map(x=>x.id===g.id?{...x,checked:!x.checked}:x))}>{g.checked?<CheckCircle2 className="text-primary size-6"/>:<Circle className="text-muted-foreground size-6"/>}</Button><div><h3 className={g.checked?'line-through text-muted-foreground':''}>{g.name}</h3><p>{g.quantity}</p></div><span className="text-xs text-muted-foreground">Mia</span></div>)}</section>)}<Button variant="outline" className="w-full h-11" onClick={()=>ctx.setModal('grocery')}><Plus/>Add an item</Button></>:<><div className="balance-band"><span className="text-sm">October household bills</span><strong>₱{paid?'0':'2,450'}</strong><span className="text-xs text-muted-foreground">{paid?'All caught up.':'1 bill to take care of'}</span></div><div className="list-row"><span className="feature-icon bg-sky text-sky-ink"><House/></span><div><h3>Electricity</h3><p>Due October 15 · Dad</p><p>₱2,450</p></div><Button variant={paid?'soft':'mobile'} onClick={()=>setPaid(!paid)}>{paid?<><Check/>Paid</>:'Mark paid'}</Button></div></>}<Button variant="link" asChild className="w-full mt-5"><Link to="/money"><ArrowLeftRight/>Family balances<ChevronRight/></Link></Button></>;}
export function MoneyView(){const ctx=useKubo();return <><PageHeading title="Family balances" subtitle="A little give & take, all kept clear." onAdd={()=>ctx.setModal('debt')}/><div className="balance-band"><span className="text-sm">Your balance</span><strong>{ctx.debts.every(d=>d.settled)?'₱0':'−₱50'}</strong><span className="text-xs text-muted-foreground">Between you and your family</span></div><SectionTitle title="With your family"/>{ctx.debts.map(d=><div className="list-row" key={d.id}><MemberAvatar name={d.name}/><div><h3>{d.settled?'All settled':d.direction==='owe'?`You owe ${d.name}`:`${d.name} owes you`}</h3><p>{d.reason}</p><p className="font-semibold">₱{d.amount}</p></div><Button variant={d.settled?'soft':'outline'} onClick={()=>ctx.setDebts(items=>items.map(x=>x.id===d.id?{...x,settled:!x.settled}:x))}>{d.settled?<Check/>:'Settle'}</Button></div>)}<p className="prototype-note mt-6">Balances are a record between family members. No money is transferred.</p></>;}
export function FamilyView(){const ctx=useKubo();return <><PageHeading title="Your family circle" subtitle="The people who make a house a home."/><div className="balance-band flex items-center gap-4"><span className="feature-icon bg-card text-primary"><House/></span><div><h2 className="font-bold text-lg">The Santos family</h2><p className="text-xs text-muted-foreground mt-1">5 members · a whole lot of love</p></div></div>{members.map(m=><Button variant="plain" key={m.name} className="circle-card w-full h-auto justify-start text-left whitespace-normal rounded-none" onClick={()=>{ctx.setSelectedMember(m);ctx.setModal('member');}}><MemberAvatar name={m.name}/><span className="min-w-0"><h3>{m.name==='You'?'Mia (You)':m.name}</h3><p>{m.role}</p></span><ChevronRight className="text-muted-foreground"/></Button>)}<Button variant="mobile" className="w-full mt-7" onClick={()=>ctx.setModal('invite')}><Plus/>Invite a family member</Button><div className="mt-6 flex items-center justify-center gap-2 text-xs text-muted-foreground"><Heart className="size-3.5"/>Everyone belongs here.</div></>;}

function PrototypeDialogs(){
 const ctx=useKubo();const [step,setStep]=useState(0);const [name,setName]=useState('');const [detail,setDetail]=useState('');const [person,setPerson]=useState('Lola');const [magic,setMagic]=useState('');
 const close=()=>{ctx.setModal(null);setStep(0);setName('');setDetail('');setMagic('');};
 const kind=ctx.modal;const titles={magic:'A little magic',scan:step?'Review your medicine':'Scan a medicine',medicine:'Add a medicine',event:'A moment together',grocery:'Add to your list',debt:'Add a family balance',invite:'Grow your circle',notifications:'Family updates',member:ctx.selectedMember?.name==='You'?'Mia':ctx.selectedMember?.name??'Family member'};
 const save=()=>{if(!name.trim())return;if(kind==='medicine'||kind==='scan')ctx.setMedicines(items=>[...items,{id:Date.now(),name:name.trim(),dosage:detail||'Confirm dosage',person,time:'8:00 AM',stock:30,status:'Upcoming',type:'Maintenance'}]);if(kind==='event')ctx.setEvents(items=>[...items,{id:Date.now(),title:name.trim(),day:9,time:detail||'3:00 PM',member:person,location:'At home'}]);if(kind==='grocery')ctx.setGroceries(items=>[...items,{id:Date.now(),name:name.trim(),category:'Pantry',checked:false,quantity:detail||'1 item'}]);if(kind==='debt')ctx.setDebts(items=>[...items,{id:Date.now(),name:person,amount:Number(detail)||0,reason:name.trim(),direction:'owe',settled:false}]);close();ctx.notify('Added to your family · preview');};
 return <Dialog open={kind!==null} onOpenChange={open=>{if(!open)close();}}><DialogContent className="max-w-[440px] w-[calc(100%-32px)] rounded-lg max-h-[85dvh] overflow-y-auto gap-5"><DialogTitle className="font-display text-xl font-extrabold">{kind?titles[kind]:''}</DialogTitle><DialogDescription className="sr-only">Kubo household preview</DialogDescription>
 {kind==='notifications'&&<>{ctx.events[0]&&<EventRow event={ctx.events[0]}/>} <div className="list-row"><Pill className="text-primary"/><div><h3>Lola’s morning medicine</h3><p>Losartan · 8:00 AM</p></div><span className="pill-label bg-peach text-peach-ink">Due now</span></div><p className="prototype-note">Sample family updates</p></>}
 {kind==='member'&&ctx.selectedMember&&<><div className="flex items-center gap-4"><MemberAvatar name={ctx.selectedMember.name}/><div><h3 className="font-bold">{ctx.selectedMember.role}</h3><p className="text-sm text-muted-foreground">Santos family</p></div></div><div className="list-row"><CalendarDays/><div><h3>Birthday</h3><p>{ctx.selectedMember.birthday}</p></div></div><div className="flex gap-2 items-center text-sm text-primary"><ShieldCheck className="size-4"/>Part of your family circle</div></>}
 {kind==='invite'&&<><p className="text-sm text-muted-foreground">An open door for someone you love.</p><div className="bg-secondary rounded-lg p-6 text-center"><p className="text-xs text-muted-foreground mb-3">FAMILY INVITE CODE</p><h3 className="font-display text-3xl font-bold">KUBO-0524</h3></div><Button variant="mobile" onClick={()=>ctx.notify('Sample invite code copied · preview')}><Copy/>Copy invite code</Button><p className="prototype-note">Preview code only. Invitations aren’t sent in this prototype.</p></>}
 {kind==='scan'&&step===0&&<><div className="scan-stage"><div className="scan-frame"><Pill className="size-12"/></div><h3 className="font-bold text-sm">Medicine box or prescription</h3><p className="text-xs text-muted-foreground mt-2">Sample scan · no photo is processed</p></div><Button variant="mobile" onClick={()=>{setName('Losartan');setDetail('50 mg · 1 tablet');setStep(1);}}><Camera/>Try sample scan</Button><Button variant="link" onClick={()=>{ctx.setModal('medicine');setStep(0);}}>Enter details manually</Button></>}
 {(kind==='medicine'||kind==='grocery'||kind==='event'||kind==='debt'||(kind==='scan'&&step===1))&&<form className="grid gap-4" onSubmit={e=>{e.preventDefault();save();}}>{kind==='scan'&&<span className="pill-label bg-secondary text-primary w-fit"><Check/>Sample scan ready to review</span>}<label className="form-field">{kind==='event'?'Event title':kind==='debt'?'What was it for?':kind==='grocery'?'Item name':'Medicine name'}<Input required value={name} onChange={e=>setName(e.target.value)} placeholder={kind==='grocery'?'e.g. Fresh milk':kind==='debt'?'e.g. Pizza night':kind==='event'?'e.g. Family dinner':'e.g. Losartan'}/></label><label className="form-field">{kind==='event'?'Time':kind==='debt'?'Amount (₱)':kind==='grocery'?'Quantity':'Dosage — confirm before saving'}<Input value={detail} onChange={e=>setDetail(e.target.value)} type={kind==='debt'?'number':'text'} min={kind==='debt'?1:undefined} placeholder={kind==='grocery'?'1 carton':kind==='debt'?'200':kind==='event'?'3:00 PM':'50 mg · 1 tablet'}/></label>{kind!=='grocery'&&<label className="form-field">{kind==='debt'?'You owe':'Family member'}<select className="h-11 rounded-md border border-input bg-background px-3 text-base" value={person} onChange={e=>setPerson(e.target.value)}>{members.map(m=><option key={m.name}>{m.name}</option>)}</select></label>}{kind==='event'&&<p className="prototype-note">This preview adds the event on October 9, 2026.</p>}{(kind==='medicine'||kind==='scan')&&<p className="prototype-note">Follow your doctor’s or pharmacist’s instructions. Nothing is saved until you confirm.</p>}<Button variant="mobile" type="submit">{kind==='scan'?'Confirm medicine':'Add to family'}</Button></form>}
 {kind==='magic'&&<>{step===0?<><p className="text-sm text-muted-foreground">What’s on your mind?</p><Textarea rows={4} value={magic} onChange={e=>setMagic(e.target.value)} placeholder="Bili gatas bukas, bayad kay Kuya 200 pizza, check-up ni Lola Biyernes 3pm"/><p className="prototype-note">Sample AI preview. Your text stays in this screen.</p><Button variant="mobile" disabled={!magic.trim()} onClick={()=>setStep(1)}><Sparkles/>Preview magic add</Button><Button variant="link" onClick={()=>setMagic('Bili gatas bukas, bayad kay Kuya 200 pizza, check-up ni Lola Biyernes 3pm')}>Try a sample</Button></>:<><p className="prototype-note">Sample results, not an analysis of your text.</p><div className="list-row"><ShoppingBasket className="text-peach-ink"/><div><h3>Fresh milk</h3><p>Grocery · Dairy & eggs</p></div><Check className="text-primary"/></div><div className="list-row"><Wallet className="text-lilac-ink"/><div><h3>You owe Kuya ₱200</h3><p>Pizza</p></div><Check className="text-primary"/></div><div className="list-row"><CalendarDays className="text-sky-ink"/><div><h3>Lola’s check-up</h3><p>October 16 · 3:00 PM</p></div><Check className="text-primary"/></div><Button variant="mobile" onClick={()=>{ctx.setGroceries(items=>[...items,{id:Date.now(),name:'Fresh milk',category:'Dairy & eggs',quantity:'1 carton',checked:false}]);ctx.setDebts(items=>[...items,{id:Date.now(),name:'Kuya',amount:200,reason:'Pizza',direction:'owe',settled:false}]);ctx.setEvents(items=>[...items,{id:Date.now(),title:'Lola’s check-up',day:16,time:'3:00 PM',member:'Lola',location:'Clinic'}]);close();ctx.notify('3 sample items added');}}><Check/>Confirm 3 items</Button><Button variant="plain" onClick={()=>setStep(0)}>Back to your note</Button></>}</>}
 </DialogContent></Dialog>;
}
